# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [2]:
mat1 = np.random.randint(10, size=(3,3))
mat2 = np.random.randint(50, size=(3,3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[0 3 8]
 [2 8 0]
 [7 5 3]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[45 23  1]
 [34  8 15]
 [16 12 36]]


In [3]:
print("\nAddition\n------------------\n", mat1+mat2)


Addition
------------------
 [[45 26  9]
 [36 16 15]
 [23 17 39]]


In [4]:
print("\nMultiplication\n------------------\n", mat1*mat2)


Multiplication
------------------
 [[  0  69   8]
 [ 68  64   0]
 [112  60 108]]


In [6]:
print("\nDivision\n------------------\n", mat1/mat2)


Division
------------------
 [[0.         0.13043478 8.        ]
 [0.05882353 1.         0.        ]
 [0.4375     0.41666667 0.08333333]]


In [8]:
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Linear combination: 3*A - 2*B
-----------------------------
 [[-90 -37  22]
 [-62   8 -30]
 [-11  -9 -63]]


In [9]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


Addition of a scalar (100)
-------------------------
 [[100 103 108]
 [102 108 100]
 [107 105 103]]


In [10]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)


Exponentiation, matrix cubed here
----------------------------------------
 [[  0  27 512]
 [  8 512   0]
 [343 125  27]]


In [11]:
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[0.         1.73205081 2.82842712]
 [1.41421356 2.82842712 0.        ]
 [2.64575131 2.23606798 1.73205081]]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [12]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = np.array(ri(1,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[6 3 6]
 [9 7 1]
 [6 3 3]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[3 1 2]
 [7 4 4]
 [8 2 5]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 44

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [21 13 10]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [15 17 12]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [108  63  54]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [168   8  40]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.888888888888889

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [13]:
import numpy as np
from numpy.random import randint as ri
mat1 = np.array(ri(1,100,9)).reshape(9,1)
mat1

array([[ 9],
       [90],
       [68],
       [ 8],
       [50],
       [89],
       [ 2],
       [71],
       [89]])

### 4.Sort

In [14]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [ 1 28 33 87 26 18 58 45 83 88]

Here is the sorted vector
 -------------------------------------------------- 
 [ 1 18 26 28 33 45 58 83 87 88]


In [15]:
M = ri(1,100,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[65 74 69 33 12]
 [ 3 62 57 50 66]
 [88  9  4 11 63]
 [59 87 24  8 68]
 [87 91 25 62 90]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[12 33 65 69 74]
 [ 3 50 57 62 66]
 [ 4  9 11 63 88]
 [ 8 24 59 68 87]
 [25 62 87 90 91]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 3  9  4  8 12]
 [59 62 24 11 63]
 [65 74 25 33 66]
 [87 87 57 50 68]
 [88 91 69 62 90]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [19]:
# Fill the following ***** with appropriate solution.
from numpy.random import randint as ri
a=ri(1,100,10)
b=ri(5,50,10)
c=ri(7,200,10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", a.max())
print("Max of b:",b.max())


print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

print("Min of a:", a.min())
print("Min of b:", b.min())


print("Min of a location:", a.argmin())
print("Min of b location:", b.argmin())
print("Min of c location:", c.argmin())



a: [53 43 38 75 14 85 50 43 76 71]
b: [15 13 12 24 21 23 18 25 38 23]
c: [187  56  52  85  94  95 176 171 161  57]
Max of a: 85
Max of b: 38
Max of a location: 5
Max of b location: 8
Max of c location: 0
Min of a: 14
Min of b: 12
Min of a location: 4
Min of b location: 2
Min of c location: 2


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [26]:

mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[4 8 2]
 [2 5 1]
 [8 9 3]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 4 8]
 [5 2 3]
 [1 1 6]]

Sq-root of 1st matrix using np
------------------
 [[2.         2.82842712 1.41421356]
 [1.41421356 2.23606798 1.        ]
 [2.82842712 3.         1.73205081]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[5.45981500e+01 2.98095799e+03 7.38905610e+00]
 [7.38905610e+00 1.48413159e+02 2.71828183e+00]
 [2.98095799e+03 8.10308393e+03 2.00855369e+01]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.60205999 0.90308999 0.30103   ]
 [0.30103    0.69897    0.        ]
 [0.90308999 0.95424251 0.47712125]]

Modulo reminder using np
 -------------------------------------------------- 
 [[4 0 2]
 [2 1 1]
 [0 0 3]]


### 7.Generating matrices from distributions

In [25]:

print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.33640762 0.00211004 0.3401205 ]
 [0.25170121 0.23656147 0.77653823]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 1.58638311  1.35937307 -0.68964232]
 [-0.07970514 -0.14846954  0.58592952]
 [ 0.94472068  0.64528868  0.23324081]
 [ 0.83339807  0.25175885 -1.14229103]]
Random integer vector: [69 22 12 37 46 45 66 69 92 99]

Random integer matrix
[[61 61  3 92]
 [24 13 97 58]
 [67 12  4 89]
 [71 65 27 53]]

20 samples drawn from a dice throw: [5 4 3 1 4 3 3 2 4 5 2 1 4 2 5 2 4 6 1 4]


### 8.Find the nearest value from a given number in an array using NumPy.

In [24]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element
import numpy as np
x = np.random.uniform(1, 12, 5)
print(x)
print("\nInput array\n","-"*50,"\n",x)
v = 10
n = x[np.abs(x - v).argmin()]
print(n)

[6.2780474  8.13071178 4.30503282 9.799651   1.59500155]

Input array
 -------------------------------------------------- 
 [6.2780474  8.13071178 4.30503282 9.799651   1.59500155]
9.799651002096097


In [20]:
import numpy as np
x = np.random.uniform(1, 12, 5)  #Create an array of 5 random element from 1 to 12
x

array([7.24755439, 3.23890809, 7.70361317, 9.52527773, 3.66821749])

In [21]:
v = 10                              #Suppose find the nearest values of 10 in an array so set value=10
n = x.flat[np.abs(x - v).argmin()]  #find the index where difference is minimum and get the element
print(n)

9.52527772627717


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [22]:
import numpy as np
print(np.fromfunction(lambda i, j: i*j, (3, 3), dtype=int))

[[0 0 0]
 [0 1 2]
 [0 2 4]]
